version: "3.7"
services:
  nodeapp:
    build:
      context: ./name-tinder-backend
    container_name: name-node
    volumes:
      - ./name-tinder-backend:/app
    depends_on:
      - database
    restart: on-failure
    environment:
      - DB_HOST=name-mongo
      - DOCKER=true
      - DB_PORT=27017
      - DB_NAME=name-tinder
    networks:
      - app
    ports:
      - 8880:8793
    command: ["npm", "run", "docker"] #启动时后的命令

  database:
    # image: mongo
    build:
      context: ./mongodb
    container_name: name-mongo
    # volumes:
    #   - ./mongodb/data/db:/data/db
    restart: always
    ports:
      - 27020:27017
    networks:
      - app

networks:
  app:
